#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10
bspc config normal_border_color	"#ffffff"
bspc config focus_border_color	"#000000"
bspc config active_border_color "#a2e1fd"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh --hack
feh --bg-fill /mnt/dd1c74f7-7296-478c-8b1b-f37d7368b499/thumb-1920-1086533.jpg 
ibus-daemon -drx
